### ISSUE TITLE
Add flobits to flovatarstarbattle

### ISSUE THREAD

**Issue by C-3PFLO** [emerald-dao/emerald-bot#8]
Currently `flovatarstarbattle` only supports `str == "B66H" || str2 == "C166" || str2 == "C167" || str2 == "C168"`, ie: yoda body or one of the star ranger suits.
https://github.com/emerald-dao/emerald-bot/blob/4129ef173e8591f3cbb912c3d33f0817bca48188/flow/holdings/nftholdings.js#L348

I propose we add `|| accessoryId == UInt64(17) || accessoryId == UInt64(18) || accessoryId == UInt64(19)` to support any of the three lightsabers.  We could also add background 478 for astrobattles (is it `backgroundId == UInt64(478)`?).

I'd be happy to create a pull request for this but think I need to be invited as a collaborator (tried to push a branch and got a 403).  Also not sure how to test before requesting to merge...

@crash13override thoughts?

**Comment by crash13override** [comment]
I think you have to fork the repo and then create the PR based on your fork to be able to submit it. At lease this is what I remember...

In any case, I will support this change, so if you manage to make the PR feel free to include me to give the green light for the merge.

Thanks!

**Comment by jacob-tucker** [comment]
Very recently we also added support for something called "entity" verification, where you only require 1 button to verify but it automatically figures out all the roles and things to check for. Maybe we could do this for Flovatar?

**Comment by crash13override** [comment]
that's awesome!!! I will definitely look into it and add the necessary code for it.
Do you have any specific link to share maybe?
